# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: Track web security compliance
subtitle: Making government websites more secure

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/project-name'

# Author/Organization info to be displayed in the templates
author:
  name: Canadian Digital Service
  url: https://digital.canada.ca
author2:
  name: Treasury Board of Canada Secretariat
  url: https://www.canada.ca/en/treasury-board-secretariat.html

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
- text: Background
  url: background/
  internal: true
- text: Features
  url: features/
  internal: true
- text: Code and repositories
  url: code-and-repositories/
  internal: true
- text: Contributing and open source
  url: contributing/
  internal: true
- text: Contact
  url: contact/
  internal: true


# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: track-web
  description: Report results
  url: https://github.com/cds-snc/track-web
- name: tracker
  description: Scan domains
  url: https://github.com/cds-snc/tracker

# Style Variables
brand_color: "#FFCC3D"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
